In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import skew, kurtosis

In [38]:
"""def compute_statistics(window):
    stats = {}
    for col in window.columns:
        if window[col].dtype in ["int64", "float64"]:  # Numeric columns
            stats[f"{col}_MinV"] = np.min(window[col], axis = 0)
            stats[f"{col}_MaxV"] = np.max(window[col], axis = 0)
            stats[f"{col}_std"] = np.std(window[col], axis = 0)
            stats[f"{col}_AM"] = np.mean(window[col], axis = 0)
            stats[f"{col}_AAM"] = np.mean(np.abs(window[col]), axis = 0)
            #stats[f"{col}_GM"] = np.exp(np.mean(np.log(window[col] + 1e-9), axis = 0))
            stats[f"{col}_HM"] = len(window[col]) / np.sum(1.0 / (window[col] + 1e-9), axis=0)
            stats[f"{col}_Sum"] = np.sum(window[col], axis=0)
            stats[f"{col}_Q1"] = np.percentile(window[col], 25, axis=0)
            stats[f"{col}_Median"] = np.median(window[col], axis=0)
            stats[f"{col}_Q3"] = np.percentile(window[col], 75, axis=0)
            stats[f"{col}_Variance"] = np.var(window[col], axis=0)
            #stats[f"{col}_Skewness"] = skew(window[col], axis=0)
            #stats[f"{col}_Kurtosis"] = kurtosis(window[col], axis=0)
            stats[f"{col}_Zero_Crossings"] = np.sum(np.diff(np.sign(window[col]), axis=0) != 0, axis=0)
            stats[f"{col}_Mean_Energy"] = np.mean(window[col]**2, axis=0)
            stats[f"{col}_Mean_Curve_Length"] = np.mean(np.abs(np.diff(window[col], axis=0)), axis=0)
            #stats[f"{col}_Mean_Teager_Energy"] = np.mean(window[col][1:-1]**2 - window[col][:-2] * window[col][2:], axis=0)

    return pd.Series(stats)


def sliding_window(df, window_size, step_size):
    aggregated_windows = []
    for start in range(0, len(df) - window_size + 1, step_size):
        end = start + window_size
        window = df.iloc[start:end]
        print(window.columns)
        #aggregated_window = compute_statistics(window)
        #aggregated_windows.append(aggregated_window)
    return pd.DataFrame(aggregated_windows)"""

In [111]:
def remove_outliers_iqr(df):
    df_cleaned = df.copy()

    for column in df_cleaned.columns:
        if pd.api.types.is_numeric_dtype(df_cleaned[column]):
            Q1 = df_cleaned[column].quantile(0.25)
            Q3 = df_cleaned[column].quantile(0.75)
            
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            
            df_cleaned = df_cleaned[(df_cleaned[column] >= lower_bound) & (df_cleaned[column] <= upper_bound)]
    
    return df_cleaned

In [4]:
labels_df = pd.read_csv("PHQ8_labels.csv")
participants = list(labels_df["Participant_ID"])
#participants = [304]
print(participants)

[300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 395, 396, 397, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492]

In [131]:
labels_df[labels_df["Participant_ID"] == 304]

   Participant_ID  PHQ8_Binary  PHQ8_Score
4             304            0           6

In [138]:

video_shape_list = []
audio_shape_list = []


for participant in participants:
    print(participant)
    # video
    au_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_AUs.txt")
    feat_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features.txt")
    feat3d_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features3D.txt")
    gaze_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_gaze.txt")
    pose_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_pose.txt")
    


    au_df.rename(columns = {" success" : " success0"}, inplace = True)
    feat_df.rename(columns = {" success" : " success1"}, inplace = True)
    feat3d_df.rename(columns = {" success" : " success2"}, inplace = True)
    gaze_df.rename(columns = {" success" : " success3"}, inplace = True)
    pose_df.rename(columns = {" success" : " success4"}, inplace = True)

    au_df.drop(columns = [" timestamp", " confidence", "frame"], inplace = True)
    feat_df.drop(columns = [" timestamp", " confidence", "frame"], inplace = True)
    feat3d_df.drop(columns = [" timestamp", " confidence", "frame"], inplace = True)
    gaze_df.drop(columns = [" timestamp", " confidence", "frame"], inplace = True)
    pose_df.drop(columns = [" timestamp", " confidence", "frame"], inplace = True)

    video_df = pd.concat([au_df, feat_df, feat3d_df, gaze_df, pose_df], axis = 1)
    
    video_df.drop(video_df.loc[video_df[" success0"]==0].index, inplace=True)
    video_df.drop(video_df.loc[video_df[" success1"]==0].index, inplace=True)
    video_df.drop(video_df.loc[video_df[" success2"]==0].index, inplace=True)
    video_df.drop(video_df.loc[video_df[" success3"]==0].index, inplace=True)
    video_df.drop(video_df.loc[video_df[" success4"]==0].index, inplace=True)
    
    video_df.drop(columns = [" success0", " success1", " success2", " success3", " success4"], inplace = True)
    

    video_df = remove_outliers_iqr(video_df)
    video_df.reset_index(drop = True, inplace = True)
    print("video:", video_df.shape)


    # audio
    formant_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_FORMANT.csv", header = None)
    formant_df.columns = ["F0", "F1", "F2", "F3", "F4"]
    covarep_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_COVAREP.csv", header = None)

    audio_df = pd.concat([formant_df, covarep_df], axis = 1)
    audio_df.dropna(inplace = True)

    audio_df.drop(audio_df.loc[audio_df[1]==0].index, inplace=True)
    audio_df.drop(columns=[1], inplace = True, axis = 1)

    audio_df = remove_outliers_iqr(audio_df)
    audio_df.reset_index(drop = True, inplace = True)
    print("audio:", audio_df.shape)


    # matching the sequential rows
    merged_df = pd.concat([video_df, audio_df], axis = 1)
    merged_df.dropna(inplace = True)

    video_df = merged_df.iloc[:, :378]
    # adding target label
    video_df["Target"] = labels_df[labels_df["Participant_ID"] == participant].iloc[0,1]

    audio_df = merged_df.iloc[:, 378:]
    audio_df["Target"] = labels_df[labels_df["Participant_ID"] == participant].iloc[0,1]


    # saving csvs

    video_df.to_csv(fr"video_matchingrows\{participant}_CLNF.csv", index = False)
    audio_df.to_csv(fr"audio_matchingrows\{participant}.csv", index = False)



    print("video after split:", video_df.shape)
    print("audio after split:", audio_df.shape)

300
video: (2023, 378)
audio: (7059, 78)
video after split: (2023, 379)
audio after split: (2023, 79)
301
video: (4557, 378)
audio: (3950, 78)
video after split: (3950, 379)
audio after split: (3950, 79)
302
video: (4026, 378)
audio: (1371, 78)
video after split: (1371, 379)
audio after split: (1371, 79)
303
video: (6729, 378)
audio: (6368, 78)
video after split: (6368, 379)
audio after split: (6368, 79)
304
video: (1613, 378)
audio: (2291, 78)
video after split: (1613, 379)
audio after split: (1613, 79)
305
video: (4115, 378)
audio: (6777, 78)
video after split: (4115, 379)
audio after split: (4115, 79)
306
video: (4888, 378)
audio: (7217, 78)
video after split: (4888, 379)
audio after split: (4888, 79)
307
video: (6875, 378)
audio: (7190, 78)
video after split: (6875, 379)
audio after split: (6875, 79)
308
video: (4841, 378)
audio: (2428, 78)
video after split: (2428, 379)
audio after split: (2428, 79)
309
video: (4069, 378)
audio: (1081, 78)
video after split: (1081, 379)
audio after split: (1081, 79)
310
video: (5617, 378)
audio: (1439, 78)
video after split: (1439, 379)
audio after split: (1439, 79)
311
video: (3618, 378)
audio: (1415, 78)
video after split: (1415, 379)
audio after split: (1415, 79)
312
video: (2217, 378)
audio: (1245, 78)
video after split: (1245, 379)
audio after split: (1245, 79)
313
video: (1553, 378)
audio: (1945, 78)
video after split: (1553, 379)
audio after split: (1553, 79)
314
video: (6468, 378)
audio: (13451, 78)
video after split: (6468, 379)
audio after split: (6468, 79)
315
video: (4708, 378)
audio: (3656, 78)
video after split: (3656, 379)
audio after split: (3656, 79)
316
video: (1817, 378)
audio: (2093, 78)
video after split: (1817, 379)
audio after split: (1817, 79)
317
video: (1039, 378)
audio: (1697, 78)
video after split: (1039, 379)
audio after split: (1039, 79)
318
video: (3954, 378)
audio: (1352, 78)
video after split: (1352, 379)
audio after split: (1352, 79)
319
video: (3433, 378)
audio: (1225, 78)
video after split: (1225, 379)
audio after split: (1225, 79)
320
video: (3271, 378)
audio: (1424, 78)
video after split: (1424, 379)
audio after split: (1424, 79)
321
video: (3691, 378)
audio: (2198, 78)
video after split: (2198, 379)
audio after split: (2198, 79)
322
video: (3256, 378)
audio: (2876, 78)
video after split: (2876, 379)
audio after split: (2876, 79)
323
video: (3919, 378)
audio: (1411, 78)
video after split: (1411, 379)
audio after split: (1411, 79)
324
video: (4183, 378)
audio: (2584, 78)
video after split: (2584, 379)
audio after split: (2584, 79)
325
video: (2118, 378)
audio: (5329, 78)
video after split: (2118, 379)
audio after split: (2118, 79)
326
video: (2358, 378)
audio: (1223, 78)
video after split: (1223, 379)
audio after split: (1223, 79)
327
video: (1788, 378)
audio: (2711, 78)
video after split: (1788, 379)
audio after split: (1788, 79)
328
video: (5945, 378)
audio: (3271, 78)
video after split: (3271, 379)
audio after split: (3271, 79)
329
video: (1612, 378)
audio: (1553, 78)
video after split: (1553, 379)
audio after split: (1553, 79)
330
video: (2454, 378)
audio: (1196, 78)
video after split: (1196, 379)
audio after split: (1196, 79)
331
video: (1264, 378)
audio: (2150, 78)
video after split: (1264, 379)
audio after split: (1264, 79)
332
video: (3280, 378)
audio: (2247, 78)
video after split: (2247, 379)
audio after split: (2247, 79)
333
video: (3661, 378)
audio: (2380, 78)
video after split: (2380, 379)
audio after split: (2380, 79)
334
video: (3199, 378)
audio: (6067, 78)
video after split: (3199, 379)
audio after split: (3199, 79)
335
video: (4962, 378)
audio: (2801, 78)
video after split: (2801, 379)
audio after split: (2801, 79)
336
video: (1453, 378)
audio: (3466, 78)
video after split: (1453, 379)
audio after split: (1453, 79)
337
video: (6366, 378)
audio: (10283, 78)
video after split: (6366, 379)
audio after split: (6366, 79)
338
video: (1342, 378)
audio: (1407, 78)
video after split: (1342, 379)
audio after split: (1342, 79)
339
video: (5168, 378)
audio: (3298, 78)
video after split: (3298, 379)
audio after split: (3298, 79)
340
video: (1502, 378)
audio: (1717, 78)
video after split: (1502, 379)
audio after split: (1502, 79)
341
video: (7104, 378)
audio: (2542, 78)
video after split: (2542, 379)
audio after split: (2542, 79)
343
video: (2740, 378)
audio: (1629, 78)
video after split: (1629, 379)
audio after split: (1629, 79)
344
video: (7063, 378)
audio: (3952, 78)
video after split: (3952, 379)
audio after split: (3952, 79)
345
video: (4268, 378)
audio: (5392, 78)
video after split: (4268, 379)
audio after split: (4268, 79)
346
video: (8580, 378)
audio: (2612, 78)
video after split: (2612, 379)
audio after split: (2612, 79)
347
video: (4842, 378)
audio: (1452, 78)
video after split: (1452, 379)
audio after split: (1452, 79)
348
video: (2152, 378)
audio: (2703, 78)
video after split: (2152, 379)
audio after split: (2152, 79)
349
video: (4760, 378)
audio: (2934, 78)
video after split: (2934, 379)
audio after split: (2934, 79)
350
video: (4214, 378)
audio: (2354, 78)
video after split: (2354, 379)
audio after split: (2354, 79)
351
video: (4632, 378)
audio: (5014, 78)
video after split: (4632, 379)
audio after split: (4632, 79)
352
video: (6704, 378)
audio: (4075, 78)
video after split: (4075, 379)
audio after split: (4075, 79)
353
video: (1267, 378)
audio: (5352, 78)
video after split: (1267, 379)
audio after split: (1267, 79)
354
video: (2327, 378)
audio: (1516, 78)
video after split: (1516, 379)
audio after split: (1516, 79)
355
video: (4192, 378)
audio: (5255, 78)
video after split: (4192, 379)
audio after split: (4192, 79)
356
video: (7781, 378)
audio: (3828, 78)
video after split: (3828, 379)
audio after split: (3828, 79)
357
video: (2960, 378)
audio: (702, 78)
video after split: (702, 379)
audio after split: (702, 79)
358
video: (2651, 378)
audio: (1217, 78)
video after split: (1217, 379)
audio after split: (1217, 79)
359
video: (4026, 378)
audio: (2043, 78)
video after split: (2043, 379)
audio after split: (2043, 79)
360
video: (1632, 378)
audio: (2308, 78)
video after split: (1632, 379)
audio after split: (1632, 79)
361
video: (2140, 378)
audio: (1427, 78)
video after split: (1427, 379)
audio after split: (1427, 79)
362
video: (3039, 378)
audio: (1364, 78)
video after split: (1364, 379)
audio after split: (1364, 79)
363
video: (5974, 378)
audio: (5734, 78)
video after split: (5734, 379)
audio after split: (5734, 79)
364
video: (16032, 378)
audio: (8351, 78)
video after split: (8351, 379)
audio after split: (8351, 79)
365
video: (9272, 378)
audio: (875, 78)
video after split: (875, 379)
audio after split: (875, 79)
366
video: (14659, 378)
audio: (4050, 78)
video after split: (4050, 379)
audio after split: (4050, 79)
367

C:\Users\sachl\AppData\Local\Temp\ipykernel_8644\1287349743.py:9: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139) have mixed types. Specify dtype option on import or set low_memory=False.
  feat_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features.txt")
C:\Users\sachl\AppData\Local\Temp\ipykernel_8644\1287349743.py:10: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207) have mixed types. Specify dtype option on import or set low_memory=False.
  feat3d_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features3D.txt")

video: (6536, 378)
audio: (7567, 78)
video after split: (6536, 379)
audio after split: (6536, 79)
368
video: (12209, 378)
audio: (7476, 78)
video after split: (7476, 379)
audio after split: (7476, 79)
369
video: (9859, 378)
audio: (7511, 78)
video after split: (7511, 379)
audio after split: (7511, 79)
370
video: (6680, 378)
audio: (6978, 78)
video after split: (6680, 379)
audio after split: (6680, 79)
371
video: (4759, 378)
audio: (3086, 78)
video after split: (3086, 379)
audio after split: (3086, 79)
372
video: (4955, 378)
audio: (4245, 78)
video after split: (4245, 379)
audio after split: (4245, 79)
373
video: (5537, 378)
audio: (13155, 78)
video after split: (5537, 379)
audio after split: (5537, 79)
374
video: (7991, 378)
audio: (4876, 78)
video after split: (4876, 379)
audio after split: (4876, 79)
375
video: (3261, 378)
audio: (1618, 78)
video after split: (1618, 379)
audio after split: (1618, 79)
376
video: (1029, 378)
audio: (3713, 78)
video after split: (1029, 379)
audio after split: (1029, 79)
377
video: (5116, 378)
audio: (6953, 78)
video after split: (5116, 379)
audio after split: (5116, 79)
378
video: (4168, 378)
audio: (2961, 78)
video after split: (2961, 379)
audio after split: (2961, 79)
379
video: (3140, 378)
audio: (4104, 78)
video after split: (3140, 379)
audio after split: (3140, 79)
380
video: (21485, 378)
audio: (9001, 78)
video after split: (9001, 379)
audio after split: (9001, 79)
381
video: (4168, 378)
audio: (2546, 78)
video after split: (2546, 379)
audio after split: (2546, 79)
382
video: (3893, 378)
audio: (3595, 78)
video after split: (3595, 379)
audio after split: (3595, 79)
383
video: (10635, 378)
audio: (2455, 78)
video after split: (2455, 379)
audio after split: (2455, 79)
384
video: (8428, 378)
audio: (4244, 78)
video after split: (4244, 379)
audio after split: (4244, 79)
385
video: (1683, 378)
audio: (848, 78)
video after split: (848, 379)
audio after split: (848, 79)
386
video: (4447, 378)
audio: (6570, 78)
video after split: (4447, 379)
audio after split: (4447, 79)
387
video: (2047, 378)
audio: (1847, 78)
video after split: (1847, 379)
audio after split: (1847, 79)
388
video: (2909, 378)
audio: (786, 78)
video after split: (786, 379)
audio after split: (786, 79)
389
video: (1568, 378)
audio: (1178, 78)
video after split: (1178, 379)
audio after split: (1178, 79)
390
video: (10906, 378)
audio: (2450, 78)
video after split: (2450, 379)
audio after split: (2450, 79)
391
video: (3300, 378)
audio: (3358, 78)
video after split: (3300, 379)
audio after split: (3300, 79)
392
video: (1286, 378)
audio: (2980, 78)
video after split: (1286, 379)
audio after split: (1286, 79)
393
video: (7684, 378)
audio: (1102, 78)
video after split: (1102, 379)
audio after split: (1102, 79)
395
video: (2474, 378)
audio: (4273, 78)
video after split: (2474, 379)
audio after split: (2474, 79)
396

C:\Users\sachl\AppData\Local\Temp\ipykernel_8644\1287349743.py:9: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139) have mixed types. Specify dtype option on import or set low_memory=False.
  feat_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features.txt")
C:\Users\sachl\AppData\Local\Temp\ipykernel_8644\1287349743.py:10: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207) have mixed types. Specify dtype option on import or set low_memory=False.
  feat3d_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features3D.txt")

video: (3467, 378)
audio: (2407, 78)
video after split: (2407, 379)
audio after split: (2407, 79)
397
video: (10071, 378)
audio: (3158, 78)
video after split: (3158, 379)
audio after split: (3158, 79)
399
video: (2307, 378)
audio: (4398, 78)
video after split: (2307, 379)
audio after split: (2307, 79)
400
video: (3325, 378)
audio: (1802, 78)
video after split: (1802, 379)
audio after split: (1802, 79)
401
video: (7730, 378)
audio: (3807, 78)
video after split: (3807, 379)
audio after split: (3807, 79)
402
video: (7499, 378)
audio: (2098, 78)
video after split: (2098, 379)
audio after split: (2098, 79)
403
video: (3130, 378)
audio: (6000, 78)
video after split: (3130, 379)
audio after split: (3130, 79)
404
video: (4168, 378)
audio: (2257, 78)
video after split: (2257, 379)
audio after split: (2257, 79)
405
video: (6440, 378)
audio: (8517, 78)
video after split: (6440, 379)
audio after split: (6440, 79)
406
video: (3300, 378)
audio: (3384, 78)
video after split: (3300, 379)
audio after split: (3300, 79)
407
video: (5357, 378)
audio: (8456, 78)
video after split: (5357, 379)
audio after split: (5357, 79)
408
video: (5205, 378)
audio: (1926, 78)
video after split: (1926, 379)
audio after split: (1926, 79)
409
video: (3463, 378)
audio: (5682, 78)
video after split: (3463, 379)
audio after split: (3463, 79)
410
video: (10590, 378)
audio: (2787, 78)
video after split: (2787, 379)
audio after split: (2787, 79)
411
video: (9096, 378)
audio: (4942, 78)
video after split: (4942, 379)
audio after split: (4942, 79)
412
video: (1540, 378)
audio: (2274, 78)
video after split: (1540, 379)
audio after split: (1540, 79)
413
video: (3347, 378)
audio: (5693, 78)
video after split: (3347, 379)
audio after split: (3347, 79)
414
video: (5966, 378)
audio: (2382, 78)
video after split: (2382, 379)
audio after split: (2382, 79)
415
video: (2577, 378)
audio: (2405, 78)
video after split: (2405, 379)
audio after split: (2405, 79)
416
video: (3631, 378)
audio: (5313, 78)
video after split: (3631, 379)
audio after split: (3631, 79)
417
video: (1785, 378)
audio: (3874, 78)
video after split: (1785, 379)
audio after split: (1785, 79)
418
video: (6867, 378)
audio: (4717, 78)
video after split: (4717, 379)
audio after split: (4717, 79)
419
video: (5469, 378)
audio: (4694, 78)
video after split: (4694, 379)
audio after split: (4694, 79)
420
video: (1612, 378)
audio: (2396, 78)
video after split: (1612, 379)
audio after split: (1612, 79)
421
video: (2500, 378)
audio: (2777, 78)
video after split: (2500, 379)
audio after split: (2500, 79)
422
video: (5164, 378)
audio: (6568, 78)
video after split: (5164, 379)
audio after split: (5164, 79)
423
video: (7937, 378)
audio: (4079, 78)
video after split: (4079, 379)
audio after split: (4079, 79)
424
video: (9082, 378)
audio: (4352, 78)
video after split: (4352, 379)
audio after split: (4352, 79)
425
video: (4331, 378)
audio: (3964, 78)
video after split: (3964, 379)
audio after split: (3964, 79)
426
video: (4106, 378)
audio: (1793, 78)
video after split: (1793, 379)
audio after split: (1793, 79)
427
video: (1843, 378)
audio: (3675, 78)
video after split: (1843, 379)
audio after split: (1843, 79)
428
video: (4723, 378)
audio: (1826, 78)
video after split: (1826, 379)
audio after split: (1826, 79)
429
video: (4532, 378)
audio: (1056, 78)
video after split: (1056, 379)
audio after split: (1056, 79)
430
video: (5597, 378)
audio: (2493, 78)
video after split: (2493, 379)
audio after split: (2493, 79)
431
video: (3186, 378)
audio: (2645, 78)
video after split: (2645, 379)
audio after split: (2645, 79)
432

C:\Users\sachl\AppData\Local\Temp\ipykernel_8644\1287349743.py:9: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139) have mixed types. Specify dtype option on import or set low_memory=False.
  feat_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features.txt")
C:\Users\sachl\AppData\Local\Temp\ipykernel_8644\1287349743.py:10: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207) have mixed types. Specify dtype option on import or set low_memory=False.
  feat3d_df = pd.read_csv(fr"datasets\DAIC-Woz\{participant}_P\{participant}_CLNF_features3D.txt")

video: (4090, 378)
audio: (2301, 78)
video after split: (2301, 379)
audio after split: (2301, 79)
433
video: (1662, 378)
audio: (3040, 78)
video after split: (1662, 379)
audio after split: (1662, 79)
434
video: (10597, 378)
audio: (8136, 78)
video after split: (8136, 379)
audio after split: (8136, 79)
435
video: (1586, 378)
audio: (3647, 78)
video after split: (1586, 379)
audio after split: (1586, 79)
436
video: (2826, 378)
audio: (4089, 78)
video after split: (2826, 379)
audio after split: (2826, 79)
437
video: (2546, 378)
audio: (2565, 78)
video after split: (2546, 379)
audio after split: (2546, 79)
438
video: (7258, 378)
audio: (4318, 78)
video after split: (4318, 379)
audio after split: (4318, 79)
439
video: (10120, 378)
audio: (5972, 78)
video after split: (5972, 379)
audio after split: (5972, 79)
440
video: (9437, 378)
audio: (8439, 78)
video after split: (8439, 379)
audio after split: (8439, 79)
441
video: (7232, 378)
audio: (1637, 78)
video after split: (1637, 379)
audio after split: (1637, 79)
442
video: (3917, 378)
audio: (4197, 78)
video after split: (3917, 379)
audio after split: (3917, 79)
443
video: (3381, 378)
audio: (1291, 78)
video after split: (1291, 379)
audio after split: (1291, 79)
444
video: (4632, 378)
audio: (5669, 78)
video after split: (4632, 379)
audio after split: (4632, 79)
445
video: (2179, 378)
audio: (3065, 78)
video after split: (2179, 379)
audio after split: (2179, 79)
446
video: (8075, 378)
audio: (3553, 78)
video after split: (3553, 379)
audio after split: (3553, 79)
447
video: (4810, 378)
audio: (2536, 78)
video after split: (2536, 379)
audio after split: (2536, 79)
448
video: (6457, 378)
audio: (5678, 78)
video after split: (5678, 379)
audio after split: (5678, 79)
449
video: (8182, 378)
audio: (8091, 78)
video after split: (8091, 379)
audio after split: (8091, 79)
450
video: (9607, 378)
audio: (3564, 78)
video after split: (3564, 379)
audio after split: (3564, 79)
451
video: (1792, 378)
audio: (6044, 78)
video after split: (1792, 379)
audio after split: (1792, 79)
452
video: (5420, 378)
audio: (2082, 78)
video after split: (2082, 379)
audio after split: (2082, 79)
453
video: (5959, 378)
audio: (744, 78)
video after split: (744, 379)
audio after split: (744, 79)
454
video: (2214, 378)
audio: (1736, 78)
video after split: (1736, 379)
audio after split: (1736, 79)
455
video: (4702, 378)
audio: (2816, 78)
video after split: (2816, 379)
audio after split: (2816, 79)
456
video: (8639, 378)
audio: (3159, 78)
video after split: (3159, 379)
audio after split: (3159, 79)
457
video: (5745, 378)
audio: (1214, 78)
video after split: (1214, 379)
audio after split: (1214, 79)
458
video: (2458, 378)
audio: (8597, 78)
video after split: (2458, 379)
audio after split: (2458, 79)
459
video: (4817, 378)
audio: (2668, 78)
video after split: (2668, 379)
audio after split: (2668, 79)
461
video: (4173, 378)
audio: (3201, 78)
video after split: (3201, 379)
audio after split: (3201, 79)
462
video: (3963, 378)
audio: (3808, 78)
video after split: (3808, 379)
audio after split: (3808, 79)
463
video: (3509, 378)
audio: (3157, 78)
video after split: (3157, 379)
audio after split: (3157, 79)
464
video: (3335, 378)
audio: (3616, 78)
video after split: (3335, 379)
audio after split: (3335, 79)
465
video: (5139, 378)
audio: (5334, 78)
video after split: (5139, 379)
audio after split: (5139, 79)
466
video: (8078, 378)
audio: (4821, 78)
video after split: (4821, 379)
audio after split: (4821, 79)
467
video: (4459, 378)
audio: (1944, 78)
video after split: (1944, 379)
audio after split: (1944, 79)
468
video: (3944, 378)
audio: (3726, 78)
video after split: (3726, 379)
audio after split: (3726, 79)
469
video: (1468, 378)
audio: (6559, 78)
video after split: (1468, 379)
audio after split: (1468, 79)
470
video: (6393, 378)
audio: (4220, 78)
video after split: (4220, 379)
audio after split: (4220, 79)
471
video: (3989, 378)
audio: (4705, 78)
video after split: (3989, 379)
audio after split: (3989, 79)
472
video: (6414, 378)
audio: (1989, 78)
video after split: (1989, 379)
audio after split: (1989, 79)
473
video: (827, 378)
audio: (773, 78)
video after split: (773, 379)
audio after split: (773, 79)
474
video: (3717, 378)
audio: (3364, 78)
video after split: (3364, 379)
audio after split: (3364, 79)
475
video: (1826, 378)
audio: (2200, 78)
video after split: (1826, 379)
audio after split: (1826, 79)
476
video: (2388, 378)
audio: (1976, 78)
video after split: (1976, 379)
audio after split: (1976, 79)
477
video: (11180, 378)
audio: (3989, 78)
video after split: (3989, 379)
audio after split: (3989, 79)
478
video: (2866, 378)
audio: (2443, 78)
video after split: (2443, 379)
audio after split: (2443, 79)
479
video: (6110, 378)
audio: (1810, 78)
video after split: (1810, 379)
audio after split: (1810, 79)
480
video: (5289, 378)
audio: (2372, 78)
video after split: (2372, 379)
audio after split: (2372, 79)
481
video: (5272, 378)
audio: (1275, 78)
video after split: (1275, 379)
audio after split: (1275, 79)
482
video: (7006, 378)
audio: (3817, 78)
video after split: (3817, 379)
audio after split: (3817, 79)
483
video: (5532, 378)
audio: (5075, 78)
video after split: (5075, 379)
audio after split: (5075, 79)
484
video: (5843, 378)
audio: (4805, 78)
video after split: (4805, 379)
audio after split: (4805, 79)
485
video: (1243, 378)
audio: (1655, 78)
video after split: (1243, 379)
audio after split: (1243, 79)
486
video: (2072, 378)
audio: (1340, 78)
video after split: (1340, 379)
audio after split: (1340, 79)
487
video: (5110, 378)
audio: (4774, 78)
video after split: (4774, 379)
audio after split: (4774, 79)
488
video: (5679, 378)
audio: (3140, 78)
video after split: (3140, 379)
audio after split: (3140, 79)
489
video: (4138, 378)
audio: (882, 78)
video after split: (882, 379)
audio after split: (882, 79)
490
video: (3930, 378)
audio: (2110, 78)
video after split: (2110, 379)
audio after split: (2110, 79)
491
video: (1047, 378)
audio: (1704, 78)
video after split: (1047, 379)
audio after split: (1047, 79)
492
video: (4657, 378)
audio: (3360, 78)
video after split: (3360, 379)
audio after split: (3360, 79)

In [2]:
import os

In [3]:
audio_path = r"audio_matchingrows"
video_path = r"video_matchingrows"

In [ ]:
# saving audio combined csv

In [5]:
complete_audio_clean_matchingrows = pd.DataFrame()

for participant in participants:
    path = os.path.join(audio_path, fr"{participant}.csv")
    temp = pd.read_csv(path)


    complete_audio_clean_matchingrows = pd.concat([complete_audio_clean_matchingrows, temp], ignore_index=True, axis = 0)
    print(complete_audio_clean_matchingrows.shape)

(2023, 79)
(5973, 79)
(7344, 79)
(13712, 79)
(15325, 79)
(19440, 79)
(24328, 79)
(31203, 79)
(33631, 79)
(34712, 79)
(36151, 79)
(37566, 79)
(38811, 79)
(40364, 79)
(46832, 79)
(50488, 79)
(52305, 79)
(53344, 79)
(54696, 79)
(55921, 79)
(57345, 79)
(59543, 79)
(62419, 79)
(63830, 79)
(66414, 79)
(68532, 79)
(69755, 79)
(71543, 79)
(74814, 79)
(76367, 79)
(77563, 79)
(78827, 79)
(81074, 79)
(83454, 79)
(86653, 79)
(89454, 79)
(90907, 79)
(97273, 79)
(98615, 79)
(101913, 79)
(103415, 79)
(105957, 79)
(107586, 79)
(111538, 79)
(115806, 79)
(118418, 79)
(119870, 79)
(122022, 79)
(124956, 79)
(127310, 79)
(131942, 79)
(136017, 79)
(137284, 79)
(138800, 79)
(142992, 79)
(146820, 79)
(147522, 79)
(148739, 79)
(150782, 79)
(152414, 79)
(153841, 79)
(155205, 79)
(160939, 79)
(169290, 79)
(170165, 79)
(174215, 79)
(180751, 79)
(188227, 79)
(195738, 79)
(202418, 79)
(205504, 79)
(209749, 79)
(215286, 79)
(220162, 79)
(221780, 79)
(222809, 79)
(227925, 79)
(230886, 79)
(234026, 79)
(243027, 79)
(245573, 79)
(249168, 79)
(251623, 79)
(255867, 79)
(256715, 79)
(261162, 79)
(263009, 79)
(263795, 79)
(264973, 79)
(267423, 79)
(270723, 79)
(272009, 79)
(273111, 79)
(275585, 79)
(277992, 79)
(281150, 79)
(283457, 79)
(285259, 79)
(289066, 79)
(291164, 79)
(294294, 79)
(296551, 79)
(302991, 79)
(306291, 79)
(311648, 79)
(313574, 79)
(317037, 79)
(319824, 79)
(324766, 79)
(326306, 79)
(329653, 79)
(332035, 79)
(334440, 79)
(338071, 79)
(339856, 79)
(344573, 79)
(349267, 79)
(350879, 79)
(353379, 79)
(358543, 79)
(362622, 79)
(366974, 79)
(370938, 79)
(372731, 79)
(374574, 79)
(376400, 79)
(377456, 79)
(379949, 79)
(382594, 79)
(384895, 79)
(386557, 79)
(394693, 79)
(396279, 79)
(399105, 79)
(401651, 79)
(405969, 79)
(411941, 79)
(420380, 79)
(422017, 79)
(425934, 79)
(427225, 79)
(431857, 79)
(434036, 79)
(437589, 79)
(440125, 79)
(445803, 79)
(453894, 79)
(457458, 79)
(459250, 79)
(461332, 79)
(462076, 79)
(463812, 79)
(466628, 79)
(469787, 79)
(471001, 79)
(473459, 79)
(476127, 79)
(479328, 79)
(483136, 79)
(486293, 79)
(489628, 79)
(494767, 79)
(499588, 79)
(501532, 79)
(505258, 79)
(506726, 79)
(510946, 79)
(514935, 79)
(516924, 79)
(517697, 79)
(521061, 79)
(522887, 79)
(524863, 79)
(528852, 79)
(531295, 79)
(533105, 79)
(535477, 79)
(536752, 79)
(540569, 79)
(545644, 79)
(550449, 79)
(551692, 79)
(553032, 79)
(557806, 79)
(560946, 79)
(561828, 79)
(563938, 79)
(564985, 79)
(568345, 79)

In [8]:
display(complete_audio_clean_matchingrows)

,F0,F1,F2,F3,F4,0,2,3,4,5,...,65,66,67,68,69,70,71,72,73,Target
0,293.20,1635.5,2538.1,3242.0,3988.0,269.0,0.038446,0.111760,0.9758,0.22440,...,-0.92749,-0.74712,-0.54045,-0.42579,-0.40818,-0.27205,-0.18758,-0.115740,-0.079553,0
1,318.92,1656.0,2726.0,3413.0,4225.6,269.0,0.025810,0.080351,0.0000,0.34022,...,-0.93171,-0.74674,-0.55854,-0.43645,-0.41822,-0.27231,-0.18013,-0.141710,-0.093744,0
2,582.25,1469.5,2423.0,3034.3,4043.2,271.0,0.045581,0.179910,-5.3092,0.47652,...,-0.98807,-0.77188,-0.59350,-0.41623,-0.29127,-0.19868,-0.11678,-0.124110,-0.113760,0
3,476.97,2103.9,3067.2,4082.9,4639.4,231.0,0.058752,0.170800,-4.2914,0.26402,...,-0.66118,-0.66544,-0.68464,-0.62956,-0.61106,-0.35705,-0.26494,-0.145970,-0.166570,0
4,507.50,1305.0,1740.2,2812.2,3542.5,182.0,0.082644,0.237140,-4.6301,0.67685,...,-0.70488,-0.71061,-0.69635,-0.60842,-0.58210,-0.39583,-0.28554,-0.204080,-0.150490,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568340,222.24,1945.2,2819.0,4040.8,4784.6,152.0,0.201670,0.548830,9.2067,0.35271,...,-0.88044,-0.56210,-0.64258,-0.57587,-0.43868,-0.30497,-0.28417,-0.144310,-0.051550,0
568341,581.16,1820.0,2496.1,3225.3,4017.1,209.0,0.034666,0.349750,5.6566,0.12914,...,-0.84567,-0.73813,-0.63178,-0.54548,-0.51871,-0.30890,-0.27262,-0.134150,-0.067753,0
568342,523.00,1251.3,2007.7,2864.9,3914.0,207.5,0.134000,0.386820,-5.1442,0.19695,...,-0.83250,-0.73273,-0.62752,-0.53681,-0.51673,-0.27603,-0.26620,-0.111950,-0.042231,0
568343,523.00,852.0,1765.2,2886.5,4060.9,206.0,0.162830,0.502370,10.1350,0.21850,...,-0.86057,-0.74837,-0.61421,-0.49968,-0.47533,-0.19490,-0.19090,-0.020043,0.059151,0
568344,785.02,1347.9,2336.6,3478.9,4289.0,202.5,0.133750,0.445950,8.7460,0.16720,...,-0.86161,-0.74151,-0.58275,-0.45209,-0.43658,-0.12671,-0.10768,0.076616,0.170070,0

In [9]:
complete_audio_clean_matchingrows["Target"].value_counts()

Target
0    397624
1    170721
Name: count, dtype: int64

In [6]:
complete_audio_clean_matchingrows.to_csv("complete_audio_clean_matchingrows.csv", index = False)

In [7]:
# saving video combined csv

In [10]:
complete_video_clean_matchingrows = pd.DataFrame()


for participant in participants:
    print(participant)
    path = os.path.join(video_path, fr"{participant}_CLNF.csv")
    temp = pd.read_csv(path)


    complete_video_clean_matchingrows = pd.concat([complete_video_clean_matchingrows, temp], ignore_index=True, axis = 0)
    print(complete_video_clean_matchingrows.shape)

300
(2023, 379)
301
(5973, 379)
302
(7344, 379)
303
(13712, 379)
304
(15325, 379)
305
(19440, 379)
306
(24328, 379)
307
(31203, 379)
308
(33631, 379)
309
(34712, 379)
310
(36151, 379)
311
(37566, 379)
312
(38811, 379)
313
(40364, 379)
314
(46832, 379)
315
(50488, 379)
316
(52305, 379)
317
(53344, 379)
318
(54696, 379)
319
(55921, 379)
320
(57345, 379)
321
(59543, 379)
322
(62419, 379)
323
(63830, 379)
324
(66414, 379)
325
(68532, 379)
326
(69755, 379)
327
(71543, 379)
328
(74814, 379)
329
(76367, 379)
330
(77563, 379)
331
(78827, 379)
332
(81074, 379)
333
(83454, 379)
334
(86653, 379)
335
(89454, 379)
336
(90907, 379)
337
(97273, 379)
338
(98615, 379)
339
(101913, 379)
340
(103415, 379)
341
(105957, 379)
343
(107586, 379)
344
(111538, 379)
345
(115806, 379)
346
(118418, 379)
347
(119870, 379)
348
(122022, 379)
349
(124956, 379)
350
(127310, 379)
351
(131942, 379)
352
(136017, 379)
353
(137284, 379)
354
(138800, 379)
355
(142992, 379)
356
(146820, 379)
357
(147522, 379)
358
(148739, 379)
359
(150782, 379)
360
(152414, 379)
361
(153841, 379)
362
(155205, 379)
363
(160939, 379)
364
(169290, 379)
365
(170165, 379)
366
(174215, 379)
367
(180751, 379)
368
(188227, 379)
369
(195738, 379)
370
(202418, 379)
371
(205504, 379)
372
(209749, 379)
373
(215286, 379)
374
(220162, 379)
375
(221780, 379)
376
(222809, 379)
377
(227925, 379)
378
(230886, 379)
379
(234026, 379)
380
(243027, 379)
381
(245573, 379)
382
(249168, 379)
383
(251623, 379)
384
(255867, 379)
385
(256715, 379)
386
(261162, 379)
387
(263009, 379)
388
(263795, 379)
389
(264973, 379)
390
(267423, 379)
391
(270723, 379)
392
(272009, 379)
393
(273111, 379)
395
(275585, 379)
396
(277992, 379)
397
(281150, 379)
399
(283457, 379)
400
(285259, 379)
401
(289066, 379)
402
(291164, 379)
403
(294294, 379)
404
(296551, 379)
405
(302991, 379)
406
(306291, 379)
407
(311648, 379)
408
(313574, 379)
409
(317037, 379)
410
(319824, 379)
411
(324766, 379)
412
(326306, 379)
413
(329653, 379)
414
(332035, 379)
415
(334440, 379)
416
(338071, 379)
417
(339856, 379)
418
(344573, 379)
419
(349267, 379)
420
(350879, 379)
421
(353379, 379)
422
(358543, 379)
423
(362622, 379)
424
(366974, 379)
425
(370938, 379)
426
(372731, 379)
427
(374574, 379)
428
(376400, 379)
429
(377456, 379)
430
(379949, 379)
431
(382594, 379)
432
(384895, 379)
433
(386557, 379)
434
(394693, 379)
435
(396279, 379)
436
(399105, 379)
437
(401651, 379)
438
(405969, 379)
439
(411941, 379)
440
(420380, 379)
441
(422017, 379)
442
(425934, 379)
443
(427225, 379)
444
(431857, 379)
445
(434036, 379)
446
(437589, 379)
447
(440125, 379)
448
(445803, 379)
449
(453894, 379)
450
(457458, 379)
451
(459250, 379)
452
(461332, 379)
453
(462076, 379)
454
(463812, 379)
455
(466628, 379)
456
(469787, 379)
457
(471001, 379)
458
(473459, 379)
459
(476127, 379)
461
(479328, 379)
462
(483136, 379)
463
(486293, 379)
464
(489628, 379)
465
(494767, 379)
466
(499588, 379)
467
(501532, 379)
468
(505258, 379)
469
(506726, 379)
470
(510946, 379)
471
(514935, 379)
472
(516924, 379)
473
(517697, 379)
474
(521061, 379)
475
(522887, 379)
476
(524863, 379)
477
(528852, 379)
478
(531295, 379)
479
(533105, 379)
480
(535477, 379)
481
(536752, 379)
482
(540569, 379)
483
(545644, 379)
484
(550449, 379)
485
(551692, 379)
486
(553032, 379)
487
(557806, 379)
488
(560946, 379)
489
(561828, 379)
490
(563938, 379)
491
(564985, 379)
492
(568345, 379)

In [11]:
display(complete_video_clean_matchingrows)

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,AU10_r,AU12_r,AU14_r,AU15_r,...,x_h1,y_h1,z_h1,Tx,Ty,Tz,Rx,Ry,Rz,Target
0,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.169596,0.411488,-0.895497,24.34710,47.5664,535.164,0.198389,0.055638,-0.117204,0
1,0.000000,0.0,0.574712,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.156311,0.412949,-0.897240,24.00500,47.6058,534.351,0.202752,0.053431,-0.116840,0
2,0.000000,0.0,0.516607,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.144607,0.401512,-0.904365,11.48700,47.4767,533.786,0.205838,0.078339,-0.136158,0
3,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.143316,0.440597,-0.886191,8.98588,50.1869,533.380,0.236301,0.087538,-0.146588,0
4,0.000000,0.0,0.508391,0.0,0.0,0.53615,0.0,0.0,0.0,0.0,...,-0.166556,0.422581,-0.890890,9.34586,50.1033,534.246,0.226615,0.091649,-0.148060,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
568340,0.520283,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.445046,0.190221,-0.875072,100.78900,80.4818,612.787,0.102507,0.052492,0.078945,0
568341,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.446359,0.180351,-0.876491,100.99200,80.6265,613.252,0.100756,0.054022,0.079229,0
568342,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.408466,0.178801,-0.895090,101.43900,80.6040,614.223,0.099579,0.048727,0.076895,0
568343,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.405196,0.182628,-0.895803,101.38300,80.5637,613.862,0.101123,0.047389,0.076082,0
568344,0.000000,0.0,0.000000,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.426716,0.186983,-0.884845,101.80100,80.8755,616.149,0.106101,0.054058,0.076517,0

In [12]:
complete_video_clean_matchingrows["Target"].value_counts()

Target
0    397624
1    170721
Name: count, dtype: int64

In [13]:
complete_video_clean_matchingrows.to_csv("complete_video_clean_matchingrows.csv", index = False)