In [5]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import MinMaxScaler
from scipy.stats import skew, kurtosis

In [6]:
labels_df = pd.read_csv("PHQ8_labels.csv")
participants = list(labels_df["Participant_ID"])
#participants = [304]
print(participants)

[300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 395, 396, 397, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492]

# official training split

In [8]:
training_labels = pd.read_csv(r"datasets\DAIC-Woz\train_split_Depression_AVEC2017.csv")
training_ids = list(training_labels["Participant_ID"])
display(training_labels)
print(training_ids)

,Participant_ID,PHQ8_Binary,PHQ8_Score,Gender,PHQ8_NoInterest,PHQ8_Depressed,PHQ8_Sleep,PHQ8_Tired,PHQ8_Appetite,PHQ8_Failure,PHQ8_Concentrating,PHQ8_Moving
0,303,0,0,0,0,0,0.0,0,0,0,0,0
1,304,0,6,0,0,1,1.0,2,2,0,0,0
2,305,0,7,1,0,1,1.0,2,2,1,0,0
3,310,0,4,1,1,1,0.0,0,0,1,1,0
4,312,0,2,1,0,0,1.0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
102,485,0,2,1,0,1,0.0,0,0,0,0,1
103,486,0,4,0,1,1,0.0,1,0,1,0,0
104,487,0,0,0,0,0,0.0,0,0,0,0,0
105,488,0,0,0,0,0,0.0,0,0,0,0,0
106,491,0,8,0,1,1,1.0,1,1,1,1,1

[303, 304, 305, 310, 312, 313, 315, 316, 317, 318, 319, 320, 321, 322, 324, 325, 326, 327, 328, 330, 333, 336, 338, 339, 340, 341, 343, 344, 345, 347, 348, 350, 351, 352, 353, 355, 356, 357, 358, 360, 362, 363, 364, 366, 368, 369, 370, 371, 372, 374, 375, 376, 379, 380, 383, 385, 386, 391, 392, 393, 397, 400, 401, 402, 409, 412, 414, 415, 416, 419, 423, 425, 426, 427, 428, 429, 430, 433, 434, 437, 441, 443, 444, 445, 446, 447, 448, 449, 454, 455, 456, 457, 459, 463, 464, 468, 471, 473, 474, 475, 478, 479, 485, 486, 487, 488, 491]

In [9]:
# training csv audio
training_audio = pd.DataFrame()

for id in training_ids:
    print(id)
    temp = pd.read_csv(fr"audio_matchingrows\{id}.csv")

    training_audio = pd.concat([training_audio, temp], ignore_index = True, axis = 0)
    print(training_audio.shape)

303
(6368, 79)
304
(7981, 79)
305
(12096, 79)
310
(13535, 79)
312
(14780, 79)
313
(16333, 79)
315
(19989, 79)
316
(21806, 79)
317
(22845, 79)
318
(24197, 79)
319
(25422, 79)
320
(26846, 79)
321
(29044, 79)
322
(31920, 79)
324
(34504, 79)
325
(36622, 79)
326
(37845, 79)
327
(39633, 79)
328
(42904, 79)
330
(44100, 79)
333
(46480, 79)
336
(47933, 79)
338
(49275, 79)
339
(52573, 79)
340
(54075, 79)
341
(56617, 79)
343
(58246, 79)
344
(62198, 79)
345
(66466, 79)
347
(67918, 79)
348
(70070, 79)
350
(72424, 79)
351
(77056, 79)
352
(81131, 79)
353
(82398, 79)
355
(86590, 79)
356
(90418, 79)
357
(91120, 79)
358
(92337, 79)
360
(93969, 79)
362
(95333, 79)
363
(101067, 79)
364
(109418, 79)
366
(113468, 79)
368
(120944, 79)
369
(128455, 79)
370
(135135, 79)
371
(138221, 79)
372
(142466, 79)
374
(147342, 79)
375
(148960, 79)
376
(149989, 79)
379
(153129, 79)
380
(162130, 79)
383
(164585, 79)
385
(165433, 79)
386
(169880, 79)
391
(173180, 79)
392
(174466, 79)
393
(175568, 79)
397
(178726, 79)
400
(180528, 79)
401
(184335, 79)
402
(186433, 79)
409
(189896, 79)
412
(191436, 79)
414
(193818, 79)
415
(196223, 79)
416
(199854, 79)
419
(204548, 79)
423
(208627, 79)
425
(212591, 79)
426
(214384, 79)
427
(216227, 79)
428
(218053, 79)
429
(219109, 79)
430
(221602, 79)
433
(223264, 79)
434
(231400, 79)
437
(233946, 79)
441
(235583, 79)
443
(236874, 79)
444
(241506, 79)
445
(243685, 79)
446
(247238, 79)
447
(249774, 79)
448
(255452, 79)
449
(263543, 79)
454
(265279, 79)
455
(268095, 79)
456
(271254, 79)
457
(272468, 79)
459
(275136, 79)
463
(278293, 79)
464
(281628, 79)
468
(285354, 79)
471
(289343, 79)
473
(290116, 79)
474
(293480, 79)
475
(295306, 79)
478
(297749, 79)
479
(299559, 79)
485
(300802, 79)
486
(302142, 79)
487
(306916, 79)
488
(310056, 79)
491
(311103, 79)

In [10]:
display(training_audio)

,F0,F1,F2,F3,F4,0,2,3,4,5,...,65,66,67,68,69,70,71,72,73,Target
0,823.81,1342.9,3023.7,3916.9,4888.1,185.0,0.18001,0.57174,8.50100,0.30417,...,-0.75188,-0.83839,-0.71535,-0.60432,-0.46031,-0.29668,-0.170960,0.027021,0.17660,0
1,855.41,1344.1,3023.3,3888.8,4893.2,185.0,0.17928,0.58878,8.50920,0.29284,...,-0.75995,-0.86862,-0.74154,-0.60718,-0.47623,-0.30531,-0.176540,0.027793,0.18174,0
2,824.88,1415.5,3027.1,3862.2,4884.1,185.0,0.18413,0.53192,8.20080,0.21470,...,-0.77566,-0.89961,-0.75867,-0.59685,-0.47975,-0.30743,-0.189370,0.013804,0.18516,0
3,600.05,1141.4,2149.6,3350.3,3912.6,185.5,0.15069,0.45195,8.86010,0.18683,...,-0.82941,-0.95153,-0.76394,-0.56949,-0.50288,-0.30182,-0.154040,0.062893,0.21151,0
4,329.09,1002.7,2192.3,3424.4,4402.9,186.5,0.16770,0.47168,9.79770,0.19754,...,-0.85051,-0.97877,-0.77794,-0.57748,-0.51145,-0.28415,-0.129280,0.093830,0.20739,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311098,609.00,1089.8,2765.5,4136.7,4691.4,178.0,0.11593,0.54128,4.15840,0.32831,...,-0.75282,-0.81802,-0.69638,-0.46160,-0.35066,-0.32623,-0.057107,0.151610,0.18480,0
311099,541.28,977.0,2645.0,4051.0,4322.0,176.5,0.11106,0.57947,0.65737,0.28801,...,-0.78930,-0.81728,-0.70706,-0.49656,-0.36611,-0.31995,-0.084103,0.133270,0.17458,0
311100,504.89,1044.7,2778.6,4123.1,4690.0,176.5,0.11907,0.62939,2.77580,0.30006,...,-0.82426,-0.81302,-0.72011,-0.52942,-0.38179,-0.31599,-0.104800,0.114130,0.16517,0
311101,500.00,1315.0,2740.5,3889.7,4369.6,177.5,0.13659,0.51229,8.52860,0.23565,...,-0.85542,-0.81120,-0.73206,-0.55789,-0.39403,-0.30440,-0.110940,0.102720,0.16521,0
311102,368.99,2364.0,3380.1,4159.6,4899.7,182.0,0.16394,0.38301,10.78100,0.21550,...,-0.90033,-0.81536,-0.74276,-0.60128,-0.42893,-0.30402,-0.140830,0.070725,0.16691,0

In [11]:
training_audio["Target"].value_counts()

Target
0    226586
1     84517
Name: count, dtype: int64

In [12]:
training_audio.to_csv("training_audio.csv", index = False)

In [13]:
# training csv video
training_video = pd.DataFrame()

for id in training_ids:
    print(id)
    temp = pd.read_csv(fr"video_matchingrows\{id}_CLNF.csv")

    training_video = pd.concat([training_video, temp], ignore_index = True, axis = 0)
    print(training_video.shape)

303
(6368, 379)
304
(7981, 379)
305
(12096, 379)
310
(13535, 379)
312
(14780, 379)
313
(16333, 379)
315
(19989, 379)
316
(21806, 379)
317
(22845, 379)
318
(24197, 379)
319
(25422, 379)
320
(26846, 379)
321
(29044, 379)
322
(31920, 379)
324
(34504, 379)
325
(36622, 379)
326
(37845, 379)
327
(39633, 379)
328
(42904, 379)
330
(44100, 379)
333
(46480, 379)
336
(47933, 379)
338
(49275, 379)
339
(52573, 379)
340
(54075, 379)
341
(56617, 379)
343
(58246, 379)
344
(62198, 379)
345
(66466, 379)
347
(67918, 379)
348
(70070, 379)
350
(72424, 379)
351
(77056, 379)
352
(81131, 379)
353
(82398, 379)
355
(86590, 379)
356
(90418, 379)
357
(91120, 379)
358
(92337, 379)
360
(93969, 379)
362
(95333, 379)
363
(101067, 379)
364
(109418, 379)
366
(113468, 379)
368
(120944, 379)
369
(128455, 379)
370
(135135, 379)
371
(138221, 379)
372
(142466, 379)
374
(147342, 379)
375
(148960, 379)
376
(149989, 379)
379
(153129, 379)
380
(162130, 379)
383
(164585, 379)
385
(165433, 379)
386
(169880, 379)
391
(173180, 379)
392
(174466, 379)
393
(175568, 379)
397
(178726, 379)
400
(180528, 379)
401
(184335, 379)
402
(186433, 379)
409
(189896, 379)
412
(191436, 379)
414
(193818, 379)
415
(196223, 379)
416
(199854, 379)
419
(204548, 379)
423
(208627, 379)
425
(212591, 379)
426
(214384, 379)
427
(216227, 379)
428
(218053, 379)
429
(219109, 379)
430
(221602, 379)
433
(223264, 379)
434
(231400, 379)
437
(233946, 379)
441
(235583, 379)
443
(236874, 379)
444
(241506, 379)
445
(243685, 379)
446
(247238, 379)
447
(249774, 379)
448
(255452, 379)
449
(263543, 379)
454
(265279, 379)
455
(268095, 379)
456
(271254, 379)
457
(272468, 379)
459
(275136, 379)
463
(278293, 379)
464
(281628, 379)
468
(285354, 379)
471
(289343, 379)
473
(290116, 379)
474
(293480, 379)
475
(295306, 379)
478
(297749, 379)
479
(299559, 379)
485
(300802, 379)
486
(302142, 379)
487
(306916, 379)
488
(310056, 379)
491
(311103, 379)

In [14]:
display(training_video)

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,AU10_r,AU12_r,AU14_r,AU15_r,...,x_h1,y_h1,z_h1,Tx,Ty,Tz,Rx,Ry,Rz,Target
0,0.659856,0.0,0.000000,0.000000,0.0,0.604604,0.0,0.0,0.0,0.0,...,-0.089732,0.061428,-0.994070,39.6263,57.3311,753.640,-0.041053,0.052339,-0.062683,0
1,0.845040,0.0,0.592602,0.545399,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.080333,0.049126,-0.995557,39.6560,57.3148,752.933,-0.044771,0.055062,-0.065109,0
2,0.797575,0.0,0.000000,0.672369,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.081343,0.047745,-0.995542,39.6450,57.3013,752.489,-0.047086,0.055927,-0.066365,0
3,0.926512,0.0,0.000000,0.723597,0.0,0.643866,0.0,0.0,0.0,0.0,...,-0.081569,0.048484,-0.995488,39.6569,57.2967,752.521,-0.047474,0.056318,-0.066882,0
4,0.926970,0.0,0.000000,0.695910,0.0,0.524106,0.0,0.0,0.0,0.0,...,-0.081419,0.048296,-0.995509,39.6512,57.2988,752.471,-0.047693,0.056502,-0.067129,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311098,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.297050,-0.007900,-0.954829,109.4730,91.3100,475.020,0.079525,-0.090732,0.333802,0
311099,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.305706,-0.009472,-0.952079,109.0890,91.6197,475.025,0.078601,-0.091334,0.332607,0
311100,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.295074,-0.008215,-0.955439,108.6200,91.7337,474.379,0.086557,-0.095990,0.331868,0
311101,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.288595,0.006109,-0.957432,107.8030,91.6766,472.611,0.089232,-0.092075,0.330289,0
311102,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,...,-0.294109,0.014523,-0.955662,107.5350,91.9364,472.668,0.092108,-0.094855,0.330237,0

In [15]:
training_video["Target"].value_counts()

Target
0    226586
1     84517
Name: count, dtype: int64

In [16]:
training_video.to_csv("training_video.csv", index = False)

# official dev split

In [18]:
dev_labels = pd.read_csv(r"datasets\DAIC-Woz\dev_split_Depression_AVEC2017.csv")
dev_ids = list(dev_labels["Participant_ID"])
#display(dev_labels)
print(dev_ids)

[302, 307, 331, 335, 346, 367, 377, 381, 382, 388, 389, 390, 395, 403, 404, 406, 413, 417, 418, 420, 422, 436, 439, 440, 451, 458, 472, 476, 477, 482, 483, 484, 489, 490, 492]

In [21]:
# dev csv audio
dev_audio = pd.DataFrame()

for id in dev_ids:
    print(id)
    temp = pd.read_csv(fr"audio_matchingrows\{id}.csv")

    dev_audio = pd.concat([dev_audio, temp], ignore_index = True, axis = 0)
    print(dev_audio.shape)

302
(1371, 79)
307
(8246, 79)
331
(9510, 79)
335
(12311, 79)
346
(14923, 79)
367
(21459, 79)
377
(26575, 79)
381
(29121, 79)
382
(32716, 79)
388
(33502, 79)
389
(34680, 79)
390
(37130, 79)
395
(39604, 79)
403
(42734, 79)
404
(44991, 79)
406
(48291, 79)
413
(51638, 79)
417
(53423, 79)
418
(58140, 79)
420
(59752, 79)
422
(64916, 79)
436
(67742, 79)
439
(73714, 79)
440
(82153, 79)
451
(83945, 79)
458
(86403, 79)
472
(88392, 79)
476
(90368, 79)
477
(94357, 79)
482
(98174, 79)
483
(103249, 79)
484
(108054, 79)
489
(108936, 79)
490
(111046, 79)
492
(114406, 79)

In [22]:
display(dev_audio)

,F0,F1,F2,F3,F4,0,2,3,4,5,...,65,66,67,68,69,70,71,72,73,Target
0,637.02,1071.1,2180.2,2936.8,4318.3,108.0,0.000000,0.000000,1.73720,0.25823,...,-0.73314,-0.64574,-0.63315,-0.58484,-0.54218,-0.51263,-0.41926,-0.285890,-0.305870,0
1,727.22,1292.2,2346.1,3204.2,4013.3,108.0,0.001546,0.036668,4.15440,0.92494,...,-0.72915,-0.61964,-0.61757,-0.57222,-0.53114,-0.51390,-0.43164,-0.290190,-0.310350,0
2,690.98,1147.2,2099.6,2730.1,4161.0,109.0,0.019922,0.176990,-0.24056,0.95787,...,-0.44952,-0.41128,-0.53509,-0.57128,-0.48558,-0.28295,-0.20903,-0.290320,-0.220170,0
3,670.60,1398.0,2038.6,2851.5,4347.2,109.0,0.020144,0.150330,0.51081,1.32930,...,-0.45508,-0.41548,-0.53683,-0.58618,-0.49895,-0.29219,-0.19681,-0.282960,-0.223660,0
4,503.57,1578.0,2967.9,3611.8,4440.3,116.0,0.029841,0.152630,11.32700,0.55795,...,-0.61699,-0.52823,-0.56468,-0.54449,-0.45254,-0.35184,-0.24467,-0.336180,-0.344420,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114401,222.24,1945.2,2819.0,4040.8,4784.6,152.0,0.201670,0.548830,9.20670,0.35271,...,-0.88044,-0.56210,-0.64258,-0.57587,-0.43868,-0.30497,-0.28417,-0.144310,-0.051550,0
114402,581.16,1820.0,2496.1,3225.3,4017.1,209.0,0.034666,0.349750,5.65660,0.12914,...,-0.84567,-0.73813,-0.63178,-0.54548,-0.51871,-0.30890,-0.27262,-0.134150,-0.067753,0
114403,523.00,1251.3,2007.7,2864.9,3914.0,207.5,0.134000,0.386820,-5.14420,0.19695,...,-0.83250,-0.73273,-0.62752,-0.53681,-0.51673,-0.27603,-0.26620,-0.111950,-0.042231,0
114404,523.00,852.0,1765.2,2886.5,4060.9,206.0,0.162830,0.502370,10.13500,0.21850,...,-0.86057,-0.74837,-0.61421,-0.49968,-0.47533,-0.19490,-0.19090,-0.020043,0.059151,0
114405,785.02,1347.9,2336.6,3478.9,4289.0,202.5,0.133750,0.445950,8.74600,0.16720,...,-0.86161,-0.74151,-0.58275,-0.45209,-0.43658,-0.12671,-0.10768,0.076616,0.170070,0

In [24]:
dev_audio["Target"].value_counts()

Target
0    66089
1    48317
Name: count, dtype: int64

In [25]:
dev_audio.to_csv("dev_audio.csv", index = False)

In [26]:
# dev video
dev_video = pd.DataFrame()

for id in dev_ids:
    print(id)
    temp = pd.read_csv(fr"video_matchingrows\{id}_CLNF.csv")

    dev_video = pd.concat([dev_video, temp], ignore_index = True, axis = 0)
    print(dev_video.shape)

302
(1371, 379)
307
(8246, 379)
331
(9510, 379)
335
(12311, 379)
346
(14923, 379)
367
(21459, 379)
377
(26575, 379)
381
(29121, 379)
382
(32716, 379)
388
(33502, 379)
389
(34680, 379)
390
(37130, 379)
395
(39604, 379)
403
(42734, 379)
404
(44991, 379)
406
(48291, 379)
413
(51638, 379)
417
(53423, 379)
418
(58140, 379)
420
(59752, 379)
422
(64916, 379)
436
(67742, 379)
439
(73714, 379)
440
(82153, 379)
451
(83945, 379)
458
(86403, 379)
472
(88392, 379)
476
(90368, 379)
477
(94357, 379)
482
(98174, 379)
483
(103249, 379)
484
(108054, 379)
489
(108936, 379)
490
(111046, 379)
492
(114406, 379)

In [27]:
display(dev_video)

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,AU10_r,AU12_r,AU14_r,AU15_r,...,x_h1,y_h1,z_h1,Tx,Ty,Tz,Rx,Ry,Rz,Target
0,2.014330,0.000000,0.0,0.693384,0.0,1.86096,0.0,0.0,0.0,0.0,...,-0.177000,0.565616,-0.805450,22.1971,11.53790,475.980,0.380951,0.051183,0.069402,0
1,2.549500,0.817255,0.0,0.556519,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.156765,0.548980,-0.821003,41.4043,7.66766,465.838,0.375768,-0.095837,0.078058,0
2,2.545490,0.971113,0.0,0.523240,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.159585,0.529694,-0.833041,42.9270,7.37860,468.146,0.372503,-0.108952,0.065308,0
3,2.371040,0.657099,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.142424,0.548819,-0.823719,43.9415,6.63928,465.583,0.363121,-0.120632,0.054048,0
4,2.268890,0.897261,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.130566,0.541863,-0.830263,44.1241,6.41809,465.074,0.360095,-0.126543,0.053143,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114401,0.520283,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.445046,0.190221,-0.875072,100.7890,80.48180,612.787,0.102507,0.052492,0.078945,0
114402,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.446359,0.180351,-0.876491,100.9920,80.62650,613.252,0.100756,0.054022,0.079229,0
114403,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.408466,0.178801,-0.895090,101.4390,80.60400,614.223,0.099579,0.048727,0.076895,0
114404,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.405196,0.182628,-0.895803,101.3830,80.56370,613.862,0.101123,0.047389,0.076082,0
114405,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.0,0.0,0.0,0.0,...,-0.426716,0.186983,-0.884845,101.8010,80.87550,616.149,0.106101,0.054058,0.076517,0

In [28]:
dev_video["Target"].value_counts()

Target
0    66089
1    48317
Name: count, dtype: int64

In [29]:
dev_video.to_csv("dev_video.csv", index = False)

# official testing split

In [32]:
testing_labels = pd.read_csv(r"datasets\DAIC-Woz\test_split_Depression_AVEC2017.csv")
test_ids = list(testing_labels["participant_ID"])
print(test_ids)

[300, 301, 306, 308, 309, 311, 314, 323, 329, 332, 334, 337, 349, 354, 359, 361, 365, 373, 378, 384, 387, 396, 399, 405, 407, 408, 410, 411, 421, 424, 431, 432, 435, 438, 442, 450, 452, 453, 461, 462, 465, 466, 467, 469, 470, 480, 481]

In [34]:
# test audio csv
test_audio = pd.DataFrame()

for id in test_ids:
    print(id)
    temp = pd.read_csv(fr"audio_matchingrows\{id}.csv")

    test_audio = pd.concat([test_audio, temp], ignore_index = True, axis = 0)
    print(test_audio.shape)

300
(2023, 79)
301
(5973, 79)
306
(10861, 79)
308
(13289, 79)
309
(14370, 79)
311
(15785, 79)
314
(22253, 79)
323
(23664, 79)
329
(25217, 79)
332
(27464, 79)
334
(30663, 79)
337
(37029, 79)
349
(39963, 79)
354
(41479, 79)
359
(43522, 79)
361
(44949, 79)
365
(45824, 79)
373
(51361, 79)
378
(54322, 79)
384
(58566, 79)
387
(60413, 79)
396
(62820, 79)
399
(65127, 79)
405
(71567, 79)
407
(76924, 79)
408
(78850, 79)
410
(81637, 79)
411
(86579, 79)
421
(89079, 79)
424
(93431, 79)
431
(96076, 79)
432
(98377, 79)
435
(99963, 79)
438
(104281, 79)
442
(108198, 79)
450
(111762, 79)
452
(113844, 79)
453
(114588, 79)
461
(117789, 79)
462
(121597, 79)
465
(126736, 79)
466
(131557, 79)
467
(133501, 79)
469
(134969, 79)
470
(139189, 79)
480
(141561, 79)
481
(142836, 79)

In [35]:
display(test_audio)

,F0,F1,F2,F3,F4,0,2,3,4,5,...,65,66,67,68,69,70,71,72,73,Target
0,293.20,1635.5,2538.1,3242.0,3988.0,269.0,0.038446,0.111760,0.9758,0.22440,...,-0.92749,-0.74712,-0.54045,-0.42579,-0.40818,-0.27205,-0.18758,-0.11574,-0.079553,0
1,318.92,1656.0,2726.0,3413.0,4225.6,269.0,0.025810,0.080351,0.0000,0.34022,...,-0.93171,-0.74674,-0.55854,-0.43645,-0.41822,-0.27231,-0.18013,-0.14171,-0.093744,0
2,582.25,1469.5,2423.0,3034.3,4043.2,271.0,0.045581,0.179910,-5.3092,0.47652,...,-0.98807,-0.77188,-0.59350,-0.41623,-0.29127,-0.19868,-0.11678,-0.12411,-0.113760,0
3,476.97,2103.9,3067.2,4082.9,4639.4,231.0,0.058752,0.170800,-4.2914,0.26402,...,-0.66118,-0.66544,-0.68464,-0.62956,-0.61106,-0.35705,-0.26494,-0.14597,-0.166570,0
4,507.50,1305.0,1740.2,2812.2,3542.5,182.0,0.082644,0.237140,-4.6301,0.67685,...,-0.70488,-0.71061,-0.69635,-0.60842,-0.58210,-0.39583,-0.28554,-0.20408,-0.150490,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142831,330.85,1452.7,2163.4,2950.9,3900.8,132.0,0.065597,0.224970,-5.5836,0.10381,...,-0.62808,-0.54680,-0.64555,-0.46619,-0.48990,-0.35472,-0.30399,-0.39401,-0.196020,0
142832,322.85,1105.6,1995.6,3029.7,3898.0,132.0,0.060081,0.225120,-5.3722,0.10034,...,-0.64602,-0.56262,-0.62950,-0.47953,-0.52345,-0.37972,-0.34006,-0.39276,-0.211040,0
142833,335.45,1045.4,1943.7,3105.2,3883.2,132.0,0.065981,0.234610,-5.5856,0.10333,...,-0.66619,-0.58022,-0.61318,-0.49372,-0.53914,-0.39850,-0.36457,-0.39013,-0.226570,0
142834,333.70,1023.0,1938.7,3133.0,3880.1,132.5,0.068201,0.249390,-6.0918,0.11309,...,-0.68467,-0.59577,-0.59952,-0.50975,-0.54784,-0.41243,-0.38011,-0.38612,-0.239820,0
142835,333.15,1581.8,2017.3,3153.0,3888.2,133.5,0.070963,0.258200,-4.2097,0.12256,...,-0.69878,-0.60832,-0.58426,-0.52398,-0.55486,-0.42247,-0.39294,-0.38119,-0.253730,0

In [36]:
test_audio["Target"].value_counts()

Target
0    104949
1     37887
Name: count, dtype: int64

In [37]:
test_audio.to_csv("test_audio.csv", index = False)

In [39]:
test_video = pd.DataFrame()

for id in test_ids:
    print(id)
    temp = pd.read_csv(fr"video_matchingrows\{id}_CLNF.csv")

    test_video = pd.concat([test_video, temp], ignore_index = True, axis = 0)
    print(test_video.shape)

300
(2023, 379)
301
(5973, 379)
306
(10861, 379)
308
(13289, 379)
309
(14370, 379)
311
(15785, 379)
314
(22253, 379)
323
(23664, 379)
329
(25217, 379)
332
(27464, 379)
334
(30663, 379)
337
(37029, 379)
349
(39963, 379)
354
(41479, 379)
359
(43522, 379)
361
(44949, 379)
365
(45824, 379)
373
(51361, 379)
378
(54322, 379)
384
(58566, 379)
387
(60413, 379)
396
(62820, 379)
399
(65127, 379)
405
(71567, 379)
407
(76924, 379)
408
(78850, 379)
410
(81637, 379)
411
(86579, 379)
421
(89079, 379)
424
(93431, 379)
431
(96076, 379)
432
(98377, 379)
435
(99963, 379)
438
(104281, 379)
442
(108198, 379)
450
(111762, 379)
452
(113844, 379)
453
(114588, 379)
461
(117789, 379)
462
(121597, 379)
465
(126736, 379)
466
(131557, 379)
467
(133501, 379)
469
(134969, 379)
470
(139189, 379)
480
(141561, 379)
481
(142836, 379)

In [40]:
display(test_video)

,AU01_r,AU02_r,AU04_r,AU05_r,AU06_r,AU09_r,AU10_r,AU12_r,AU14_r,AU15_r,...,x_h1,y_h1,z_h1,Tx,Ty,Tz,Rx,Ry,Rz,Target
0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,-0.169596,0.411488,-0.895497,24.34710,47.5664,535.164,0.198389,0.055638,-0.117204,0
1,0.0,0.0,0.574712,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,-0.156311,0.412949,-0.897240,24.00500,47.6058,534.351,0.202752,0.053431,-0.116840,0
2,0.0,0.0,0.516607,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,-0.144607,0.401512,-0.904365,11.48700,47.4767,533.786,0.205838,0.078339,-0.136158,0
3,0.0,0.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,...,-0.143316,0.440597,-0.886191,8.98588,50.1869,533.380,0.236301,0.087538,-0.146588,0
4,0.0,0.0,0.508391,0.0,0.0,0.536150,0.0,0.0,0.0,0.000000,...,-0.166556,0.422581,-0.890890,9.34586,50.1033,534.246,0.226615,0.091649,-0.148060,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142831,0.0,0.0,1.017040,0.0,0.0,0.959624,0.0,0.0,0.0,0.526975,...,-0.253011,0.337232,-0.906785,68.11010,33.5450,544.832,0.129072,0.047351,-0.073179,0
142832,0.0,0.0,0.891599,0.0,0.0,1.279040,0.0,0.0,0.0,0.000000,...,-0.263330,0.354837,-0.897077,67.42680,31.6459,546.908,0.116236,0.053056,-0.074145,0
142833,0.0,0.0,0.805867,0.0,0.0,1.120620,0.0,0.0,0.0,0.000000,...,-0.280250,0.331852,-0.900741,66.50730,29.5889,546.999,0.104379,0.061790,-0.076664,0
142834,0.0,0.0,0.840307,0.0,0.0,1.147580,0.0,0.0,0.0,0.000000,...,-0.272750,0.321199,-0.906884,65.35440,27.9258,547.331,0.095918,0.069103,-0.079232,0
142835,0.0,0.0,1.302700,0.0,0.0,1.139940,0.0,0.0,0.0,0.000000,...,-0.284008,0.308265,-0.907916,64.53270,26.7625,547.385,0.084821,0.075123,-0.081372,0

In [41]:
test_video["Target"].value_counts()

Target
0    104949
1     37887
Name: count, dtype: int64

In [42]:
test_video.to_csv("test_video.csv", index = False)

# label distribution

In [45]:
training_labels["PHQ8_Binary"].value_counts()

PHQ8_Binary
0    77
1    30
Name: count, dtype: int64

In [46]:
dev_labels["PHQ8_Binary"].value_counts()

PHQ8_Binary
0    23
1    12
Name: count, dtype: int64

In [48]:
full_testing_labels = pd.read_csv(r"datasets\DAIC-Woz\full_test_split.csv")
full_testing_labels["PHQ_Binary"].value_counts()

PHQ_Binary
0    33
1    14
Name: count, dtype: int64